export const FACEBOOK_LOAD_SDK = 'FACEBOOK_LOAD_SDK';
export const FACEBOOK_LOAD_SDK_SUCCESS = 'FACEBOOK_LOAD_SDK_SUCCESS';
export const FACEBOOK_LOAD_SDK_FAILURE = 'FACEBOOK_LOAD_SDK_FAILURE';

export const FACEBOOK_LOG_IN = 'FACEBOOK_LOG_IN';
export const FACEBOOK_LOG_IN_SUCCESS = 'FACEBOOK_LOG_IN_SUCCESS';
export const FACEBOOK_LOG_IN_FAILURE = 'FACEBOOK_LOG_IN_FAILURE';

export const FACEBOOK_LOG_OUT = 'FACEBOOK_LOG_OUT';
export const FACEBOOK_LOG_OUT_SUCCESS = 'FACEBOOK_LOG_OUT_SUCCESS';
export const FACEBOOK_LOG_OUT_FAILURE = 'FACEBOOK_LOG_OUT_FAILURE';

export const FACEBOOK_GET_PICTURE = 'FACEBOOK_GET_PICTURE';
export const FACEBOOK_GET_PICTURE_SUCCESS = 'FACEBOOK_GET_PICTURE_SUCCESS';
export const FACEBOOK_GET_PICTURE_FAILURE = 'FACEBOOK_GET_PICTURE_FAILURE';

export const FACEBOOK_CHECK_STATUS = 'FACEBOOK_CHECK_STATUS';
export const FACEBOOK_CHECK_STATUS_SUCCESS = 'FACEBOOK_CHECK_STATUS_SUCCESS';
export const FACEBOOK_CHECK_STATUS_FAILURE = 'FACEBOOK_CHECK_STATUS_FAILURE';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';